export const RETRIEVE_MOVIES_GENRES_REQUEST = 'RETRIEVE_MOVIES_GENRES_REQUEST';
export const RETRIEVE_MOVIES_GENRES_SUCCESS = 'RETRIEVE_MOVIES_GENRES_SUCCESS';
export const RETRIEVE_MOVIES_GENRES_ERROR = 'RETRIEVE_MOVIES_GENRES_ERROR';

export const RETRIEVE_POPULAR_MOVIES_REQUEST =
  'RETRIEVE_POPULAR_MOVIES_REQUEST';
export const RETRIEVE_POPULAR_MOVIES_SUCCESS =
  'RETRIEVE_POPULAR_MOVIES_SUCCESS';
export const RETRIEVE_POPULAR_MOVIES_ERROR = 'RETRIEVE_POPULAR_MOVIES_ERROR';

export const RETRIEVE_NOWPLAYING_MOVIES_REQUEST =
  'RETRIEVE_NOWPLAYING_MOVIES_REQUEST';
export const RETRIEVE_NOWPLAYING_MOVIES_SUCCESS =
  'RETRIEVE_NOWPLAYING_MOVIES_SUCCESS';
export const RETRIEVE_NOWPLAYING_MOVIES_ERROR =
  'RETRIEVE_NOWPLAYING_MOVIES_ERROR';

export const RETRIEVE_MOVIES_LIST_REQUEST = 'RETRIEVE_MOVIES_LIST_REQUEST';
export const RETRIEVE_MOVIES_LIST_SUCCESS = 'RETRIEVE_MOVIES_LIST_SUCCESS';
export const RETRIEVE_MOVIES_LIST_ERROR = 'RETRIEVE_MOVIES_LIST_ERROR';

export const RETRIEVE_MOVIE_DETAILS_REQUEST = 'RETRIEVE_MOVIE_DETAILS_REQUEST';
export const RETRIEVE_MOVIE_DETAILS_SUCCESS = 'RETRIEVE_MOVIE_DETAILS_SUCCESS';
export const RETRIEVE_MOVIE_DETAILS_ERROR = 'RETRIEVE_MOVIE_DETAILS_ERROR';

export const RETRIEVE_MOVIES_SEARCH_RESULT_REQUEST =
  'RETRIEVE_MOVIES_SEARCH_RESULT_REQUEST';
export const RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS =
  'RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS';
export const RETRIEVE_MOVIES_SEARCH_RESULT_ERROR =
  'RETRIEVE_MOVIES_SEARCH_RESULT_ERROR';
